spring:
  datasource:
    driver-class-name: org.postgresql.Driver # 显式指定 PostgreSQL 驱动
    url: jdbc:postgresql://localhost:5432/lab_db # 端口改为 5432
    username: postgres
    password: 123456 # 替换为你在 PgAdmin 中设置的实际密码
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  jwt:
    secret: demo-jwt-secret-key-for-spring-security-2026
    expiration-millis: 7200000
